BackupESP fixes

diff --git a/Resources/BackupESP b/Resources/BackupESP
--- a/Resources/BackupESP
+++ b/Resources/BackupESP
@@ -10,16 +10,20 @@ if [ ! -d /Volumes/EFI/EFI ]
 then
 	DEST_VOL="$3"
 
-	DiskDevice=$(LC_ALL=C diskutil info "$DEST_VOL" 2>/dev/null | \
-	 sed -n 's/.*Part [oO]f Whole: *//p')
+	DiskDevice=$(LC_ALL=C diskutil info "$DEST_VOL" 2>/dev/null | sed -n 's/.*Part [oO]f Whole: *//p')
 	if [[ -z "$DiskDevice" ]]; then
 	    echo "Can't find volume with the name $DEST_VOL"
 	    exit 1
 	fi
 
 	# Check if the disk is a GPT disk
-	disk_partition_scheme=$(LC_ALL=C diskutil info "$DiskDevice" 2>/dev/null | \
-	 sed -nE 's/.*(Partition Type|Content \(IOContent\)): *//p')
+	disk_partition_scheme=$(LC_ALL=C diskutil info "$DiskDevice" 2>/dev/null | sed -nE 's/.*(Partition Type|Content \(IOContent\)): *//p')
+
+	if [[ "$disk_partition_scheme" = "Apple_HFS" ]]; then
+		 diskutil corestorage revert "/dev/$DiskDevice"
+		 DiskDevice=$(LC_ALL=C diskutil info "$DEST_VOL" 2>/dev/null | sed -n 's/.*Part [oO]f Whole: *//p')
+		 disk_partition_scheme=$(LC_ALL=C diskutil info "$DiskDevice" 2>/dev/null | sed -nE 's/.*(Partition Type|Content \(IOContent\)): *//p')
+	fi
 
 	if [[ "$disk_partition_scheme" = "GUID_partition_scheme" ]]; then
 
@@ -65,20 +69,46 @@ tell application "Finder"
     display dialog "Can't mount EFI partition ($ESPDevice) !
 
 Check that the partition is well formated in HFS or Fat32.
-	
+
 For format as Fat32 use command like:"
 sudo newfs_msdos -v EFI -F 32 /dev/r$ESPDevice." buttons {"OK"} default button "OK" with icon note with title "Can't mount EFI!"
 end tell
 EOT
-	        
+
 	        echo "ERROR: can't mount EFI partition ($ESPDevice) !"
 	        exit 1
 	    fi
+	else
+		while read line; do
+			device=$(echo $line |cut -d' ' -f1)
+			efidevice=`diskutil list $device | grep EFI | tr -s ' ' | awk '{print $NF}'`
+			case "$efidevice" in
+			"")	echo "This drive $device has no EFI partition.";;
+			*)	echo "Found EFI partition at /dev/$efidevice."
+				if [ "`df -h | grep /dev/$efidevice`" != "" ]
+				then
+					diskutil unmount "/dev/$efidevice" && mkdir -p /Volumes/EFI && mount -t msdos "/dev/$efidevice" /Volumes/EFI
+					echo "Mounted /dev/$efidevice at /Volumes/EFI."
+				else
+					mkdir -p /Volumes/EFI && mount -t msdos "/dev/$efidevice" /Volumes/EFI
+				fi
+				exitcode=0
+				break;;
+			esac
+		done < <(diskutil list | grep "/dev/")
 	fi
+fi
 
+if [ "$exitcode" != "0" ]
+then
+/usr/bin/osascript <<EOT
+tell application "Finder"
+activate
+display dialog "Can't find EFI partition!" buttons {"OK"} default button "OK" with icon note with title "Can't find EFI!"
+end tell
+EOT
 
-
-
+	echo "ERROR: can't mount EFI partition ($ESPDevice) !"
 fi
 
  if [ "$exitcode" == "0" ] && [ ! -d "$BackupDir/EFI" ]
@@ -94,4 +124,4 @@ fi
 	 fi
  fi
 
- exit 0
+ exit $exitcode
